_wandb:
    value:
        cli_version: 0.19.6
        m: []
        python_version: 3.11.9
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 53
                - 55
            "3":
                - 13
                - 23
                - 55
            "4": 3.11.9
            "5": 0.19.6
            "6": 4.48.0
            "8":
                - 5
            "12": 0.19.6
            "13": darwin-arm64
